// <auto-generated />
using System;
using ArtAssetManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtAssetManager.Api.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20251111153451_AddAssetParentChildRelationship")]
    partial class AddAssetParentChildRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScanFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("ParentAssetId");

                    b.HasIndex("ScanFolderId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.ScanFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("ScanFolders");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.Property<int>("AssetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("AssetTag");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtAssetManager.Api.Entities.ScanFolder", "ScanFolder")
                        .WithMany("Assets")
                        .HasForeignKey("ScanFolderId");

                    b.Navigation("Parent");

                    b.Navigation("ScanFolder");
                });

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtAssetManager.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.ScanFolder", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
