// <auto-generated />
using System;
using ArtAssetManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtAssetManager.Api.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    partial class AssetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominantColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasAlphaChannel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScanFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateAdded");

                    b.HasIndex("DominantColor");

                    b.HasIndex("FileHash");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("FileSize");

                    b.HasIndex("FileType");

                    b.HasIndex("HasAlphaChannel");

                    b.HasIndex("ImageHeight");

                    b.HasIndex("ImageWidth");

                    b.HasIndex("LastModified");

                    b.HasIndex("ParentAssetId");

                    b.HasIndex("Rating");

                    b.HasIndex("ScanFolderId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.MaterialSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoverAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomCoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverAssetId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MaterialSets");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.SavedSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SavedSearches");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.ScanFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("ScanFolders");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AssetMaterialSet", b =>
                {
                    b.Property<int>("AssetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialSetsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetsId", "MaterialSetsId");

                    b.HasIndex("MaterialSetsId");

                    b.ToTable("AssetMaterialSet");
                });

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.Property<int>("AssetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("AssetTag");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtAssetManager.Api.Entities.ScanFolder", "ScanFolder")
                        .WithMany("Assets")
                        .HasForeignKey("ScanFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("ScanFolder");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.MaterialSet", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", "CoverAsset")
                        .WithMany()
                        .HasForeignKey("CoverAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverAsset");
                });

            modelBuilder.Entity("AssetMaterialSet", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtAssetManager.Api.Entities.MaterialSet", null)
                        .WithMany()
                        .HasForeignKey("MaterialSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetTag", b =>
                {
                    b.HasOne("ArtAssetManager.Api.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtAssetManager.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.Asset", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ArtAssetManager.Api.Entities.ScanFolder", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
